print("jangan merokok")
print("stop narkoba")
print("enemy missing")
print("stop sex bebas")
print("apa kabar")
print("jangan mabuk")
print("namaewa vicky")
print("classmethod")
print("stop mabuk")
print("attack lord")