print("hallo semuanya")
nama_saya_adalah = input ("\nnama saya adalah")
print("hari ini kita akan belajar rotasi hyper ya")
hero = input("\nnama hero")
print("pertama-tama farming")
print("setelah itu kita roam ke gold lane usahakan dapat kill")
print("lalu langsung set up turtle")
item = input("\nitem awal adalah")

print("oke sampai hari ini saja pelajaran hari ini")
print("terimakasih")